TYPO3:
  PackageBuilder:
    panels:
      right:
        ElementOptionsPanel:
          header: Options Panel
          elementId: elementOptionsPanel
          emberViewClass: TYPO3.Ice.View.ElementOptionsPanelClass
          javascripts:
            sorting: 120
            files:

        ConfigurationPanel:
          header: Configuration
          elementId: configurationPanel
          emberViewClass: TYPO3.Ice.View.ConfigurationPanelClass
          javascripts:
            sorting: 130
            files:
              - 'resource://TYPO3.Ice/Public/JavaScript/Ice/view/panels/configurationPanel.js'
              - 'resource://TYPO3.Ice/Public/JavaScript/Ice/view/editors/configuration.js'

    handlebarTemplatePaths:
      'TYPO3.PackageBuilder': 'resource://TYPO3.PackageBuilder/Private/HandlebarTemplates'

    javaScripts:
      packageBuilder:
        files:
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/init.js'

          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/vendor/jsplumb/jquery.jsplumb.min.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/vendor/jsplumb/init.js'

          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/vendor/tooltip.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/vendor/popover.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/plugins/zoom.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/panels/insertElementsPanel.js'

          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/view/settings.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/panels/elementOptionsPanel.js'

          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/view/stage.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/views/component.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/views/dialogue.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/views/message.js'

          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/plugins/ember.storage.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/models/model.js'
          - 'resource://TYPO3.PackageBuilder/Public/JavaScript/modeller/models/connection.js'
        sorting: 200

    stylesheets:
      packageBuilder:
        sorting: 10
        files:
          - 'resource://TYPO3.PackageBuilder/Public/Css/PackageBuilder.css'
          - 'resource://TYPO3.PackageBuilder/Public/Css/Modeller.css'

    backport:
      targetFolder:
    extendIceSettings: TRUE
    userinterfaceSettings:
      title: Package Builder

    projectElementGroups:
      packageElements:
        sorting: 200
        label: 'Package elements'

      DomainObject:
        sorting: 400
        label: 'Model'
        enableTypes:
          - DomainObject
          - Property
          - Relation'

    projectElementTypes:
      'TYPO3.PackageBuilder:Base':
        options:
          editors:
            elementType:
              sorting: 100
              viewName: 'TYPO3.Ice.View.Editor.TextOutput'
              templateName: 'Editors-PropertyPanelTitle'

      'TYPO3.PackageBuilder:RemovableMixin':
        options:
          editors:
            removeButton:
              sorting: 999
              viewName: 'TYPO3.Ice.View.Editor.RemoveElementEditor'

      'TYPO3.PackageBuilder:ProjectElement':
        superTypes: ['TYPO3.PackageBuilder:Base', 'TYPO3.PackageBuilder:RemovableMixin']
        options:
          editors:
            label:
              label: 'Label'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.ElementOptionsPanelClass.Editor.TextEditor'

      'TYPO3.PackageBuilder:Container':
        options:
          label: ''
          _isCompositeElement: true

      'TYPO3.PackageBuilder:Package':
        options:
          label: ''
          _isCompositeElement: false
          _isTopLevel: true
          editors:
            label:
              label: 'Package Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.Editor.TextEditor'
            packageKey:
              sorting: 200
              label: 'Package key'
              propertyPath: 'identifier'
              viewName: 'TYPO3.Ice.View.Editor.TextEditor'

      # group packageElements
      'TYPO3.PackageBuilder:DomainObject':
        superTypes: ['TYPO3.PackageBuilder:ProjectElement']
        options:
          label: 'DomainObject'
          group: packageElements
          _isCompositeElement: true
          sorting: 100
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.Editor.TextEditor'
            root:
              label: 'Aggregate Root'
              propertyPath: 'root'
              sorting: 120
              viewName: 'TYPO3.Ice.View.Editor.CheckboxEditor'

      'TYPO3.PackageBuilder:Plugin':
        superTypes: ['TYPO3.PackageBuilder:ProjectElement']
        options:
          label: 'Plugin'
          group: packageElements
          sorting: 110
          editors:
            label:
              label: 'Plugin Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.Editor.TextEditor'

      'TYPO3.PackageBuilder:Module':
        superTypes: ['TYPO3.PackageBuilder:ProjectElement']
        options:
          label: 'Backend-Module'
          group: packageElements
          sorting: 120
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.Editor.TextEditor'
            key:
              label: 'Key'
              propertyPath: 'key'
              sorting: 120
              viewName: 'TYPO3.Ice.View.Editor.TextEditor'

      'TYPO3.PackageBuilder:Service':
        superTypes: ['TYPO3.PackageBuilder:ProjectElement']
        options:
          label: 'Service'
          group: packageElements
          sorting: 130
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.Editor.TextEditor'

      'TYPO3.PackageBuilder:Scheduler':
        superTypes: ['TYPO3.PackageBuilder:ProjectElement']
        options:
          label: 'Scheduler'
          group: packageElements
          sorting: 140

      'TYPO3.PackageBuilder:Property':
        superTypes: ['TYPO3.PackageBuilder:ProjectElement']
        options:
          label: 'Property'
          group: 'DomainObject'
          sorting: 120
          typeField: 'propertyType'
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.Editor.TextEditor'
            propertyType:
              sorting: 200
              label: 'Property Type'
              propertyPath: 'propertyType'
              viewName: 'TYPO3.Ice.View.Editor.SelectEditor'
              defaultValue: 'string'
              availableElements:
                0:
                  value: ['string']
                  label: 'String'
                1:
                  value: ['text']
                  label: 'Text'
                2:
                  value: ['richText']
                  label: 'RichText'
                3:
                  value: ['integer']
                  label: 'Integer'
                4:
                  value: ['float']
                  label: 'Float'
                5:
                  value: ['boolean']
                  label: 'Boolean'
                6:
                  value: ['dateTime']
                  label: 'DateTime'
                7:
                  value: ['select']
                  label: 'Select'
                8:
                  value: ['image']
                  label: 'Image'
          ## special property configuration
          configuration:
            sorting: 300
            label: 'Configuration'
            typeField: 'propertyType'
            editors:
              ## the keys on this level are the possible values of the property defined by "typeField"
              string:
                length:
                  label: 'Length'
                  key: 'length'
                  propertyPath: 'configuration'
                  sorting: 120
                  viewName: 'TYPO3.Ice.View.ConfigurationEditor.TextEditor'

              text:
                cols:
                  label: 'Cols'
                  key: 'cols'
                  propertyPath: 'configuration'
                  sorting: 120
                  viewName: 'TYPO3.Ice.View.ConfigurationEditor.TextEditor'
                rows:
                  label: 'Rows'
                  key: 'rows'
                  propertyPath: 'configuration'
                  sorting: 120
                  viewName: 'TYPO3.Ice.View.ConfigurationEditor.TextEditor'

              image:
                multiple:
                  label: 'Allowed file types'
                  key: 'fileTypes'
                  propertyPath: 'configuration'
                  sorting: 120
                  viewName: 'TYPO3.Ice.View.ConfigurationEditor.TextEditor'

              select:
                multiple:
                  label: 'Allow multiple'
                  key: 'multiple'
                  propertyPath: 'configuration'
                  sorting: 120
                  viewName: 'TYPO3.Ice.View.ConfigurationEditor.TextEditor'
                selectOptions:
                  label: 'Options'
                  key: 'selectOptions'
                  propertyPath: 'configuration'
                  sorting: 120
                  viewName: 'TYPO3.Ice.View.ConfigurationEditor.PropertyGrid'
                  isSortable: true
                  enableAddRow: true
                  enableDeleteRow: true
                  columns:
                    0:
                      field: '_value'
                      name: 'Label'
                      editor: 'TYPO3.Ice.View.ConfigurationPanel.Editor.PropertyGrid.TextCellEditor'
                    1:
                      field: '_key'
                      name: 'Value'
                      editor: 'TYPO3.Ice.View.ConfigurationPanel.Editor.PropertyGrid.TextCellEditor'



      'TYPO3.PackageBuilder:Relation':
        superTypes: ['TYPO3.PackageBuilder:ProjectElement']
        options:
          label: 'Relation'
          group: 'DomainObject'
          sorting: 120
          editors:
            label:
              label: 'Name'
              propertyPath: 'label'
              sorting: 120
              viewName: 'TYPO3.Ice.View.TextEditor'
            relationType:
              sorting: 200
              label: 'Relation Type'
              propertyPath: 'relationType'
              viewName: 'TYPO3.Ice.View.Editor.SelectEditor'
              availableElements:
                0:
                  value: ['zeroToOne']
                  label: '1:1'
                1:
                  value: ['manyToOne']
                  label: 'n:1'
                2:
                  value: ['oneToMany']
                  label: '1:n'
                3:
                  value: ['manyToMany']
                  label: 'm:n'

            selectOptions:
              label: 'Options'
              key: 'selectOptions'
              propertyPath: 'configuration.selectOptions'
              sorting: 120
              viewName: 'TYPO3.Ice.View..Editor.PropertyGrid'
              isSortable: true
              enableAddRow: true
              enableDeleteRow: true
              columns:
                0:
                  field: '_value'
                  name: 'Label'
                  editor: 'TYPO3.Ice.View.Editor.PropertyGrid.TextCellEditor'
                1:
                  field: '_key'
                  name: 'Value'
                  editor: 'TYPO3.Ice.View.ConfigurationPanel.Editor.PropertyGrid.TextCellEditor'

